module.exports = {
    'parserOptions': {
        'ecmaVersion': 8,
        'sourceType': 'module',
        'allowImportExportEverywhere': false,
        'ecmaFeatures': {
            'modules': true,
            'spread': true,
            'restParams': true
        }
    },
    // 'extends': [ 'eslint:recommended' ],
    'env': {
        'browser': true,
        'node': true,
        'es6': true
    },
    'rules': {
        'no-bitwise': 2,
        'camelcase': [ 2, { 'properties': 'never' } ],
        'curly': [ 2, 'all' ],
        'eqeqeq': 2,
        'guard-for-in': 2,
        'no-extend-native': 2,
        'wrap-iife': 0,
        'indent': [ 2, 4, { 'SwitchCase': 1 } ],
        'no-use-before-define': 0,
        'new-cap': 2,
        'no-caller': 2,
        'no-empty': 2,
        'no-irregular-whitespace': 2,
        'no-new': 2,
        'no-plusplus': 0,
        'no-undef': 2,
        'no-undef-init': 2,
        'no-undefined': 0,
        'no-unreachable': 2,
        'no-unused-vars': 2,
        'strict': 0,
        'max-params': [ 2, 10 ],
        'max-depth': [ 2, 5 ],
        'max-statements': [ 2, 40 ],
        'complexity': [ 2, 8 ],
        'max-len': [ 2, 400 ],
        'no-cond-assign': 0,
        'no-debugger': 0,
        'no-eq-null': 2,
        'no-eval': 0,
        'no-unused-expressions': 0,
        'block-scoped-var': 0,
        'no-iterator': 0,
        'no-loop-func': 2,
        'no-multi-str': 2,
        'valid-typeof': 0,
        'no-proto': 0,
        'no-script-url': 0,
        'no-shadow': 2,
        'dot-notation': 0,
        'no-new-func': 0,
        'no-new-wrappers': 0,
        'no-invalid-this': 0,
        'require-yield': 0,
        'no-mixed-spaces-and-tabs': 2,
        'no-trailing-spaces': 2,
        'space-infix-ops': 2,
        'space-before-blocks': [ 2, 'always' ],
        'space-in-parens': [ 2, 'always' ],
        'valid-jsdoc': 1,
        'array-bracket-spacing': [ 2, 'always', { 'singleValue': true } ],
        'block-spacing': 2,
        'brace-style': [ 2, 'stroustrup' ],
        'comma-spacing': [ 2, { 'before': false, 'after': true } ],
        'comma-style': 0,
        'computed-property-spacing': [ 2, 'always' ],
        'consistent-this': 0,
        'eol-last': 0,
        'func-names': 0,
        'func-style': 0,
        'id-blacklist': 0,
        'id-length': 0,
        'id-match': 0,
        'jsx-quotes': 0,
        'key-spacing': [ 2, { 'afterColon': true, 'beforeColon': false } ],
        'keyword-spacing': [ 2, { 'before': true, 'after': true, 'overrides': {} } ],
        'linebreak-style': [ 2, 'unix' ],
        'lines-around-comment': 0,
        'max-lines': 0,
        'max-nested-callbacks': 0,
        'max-statements-per-line': 0,
        'new-parens': 0,
        'newline-after-var': 0,
        'newline-before-return': 0,
        'newline-per-chained-call': 0,
        'no-array-constructor': 0,
        'no-continue': 0,
        'no-inline-comments': 0,
        'no-lonely-if': 0,
        'no-mixed-operators': 0,
        'no-multiple-empty-lines': [ 2, { 'max': 2 } ],
        'no-negated-condition': 0,
        'no-nested-ternary': 0,
        'no-new-object': 0,
        'no-restricted-syntax': 0,
        'no-spaced-func': 2,
        'no-ternary': 0,
        'no-underscore-dangle': 2,
        'no-unneeded-ternary': 0,
        'no-whitespace-before-property': 2,
        'object-curly-newline': 0,
        'object-curly-spacing': [ 2, 'always' ],
        'object-property-newline': 0,
        'one-var': 0,
        'one-var-declaration-per-line': 0,
        'operator-assignment': 0,
        'operator-linebreak': 0,
        'padded-blocks': 0,
        'quote-props': 0,
        'quotes': [ 2, 'single', { 'avoidEscape': true, 'allowTemplateLiterals': true } ],
        'require-jsdoc': 0,
        'semi': [ 2, 'always' ],
        'semi-spacing': [ 2, { 'before': false, 'after': true } ],
        'sort-vars': 0,
        'space-before-function-paren': [ 2, { 'anonymous': 'always', 'named': 'never' } ],
        'space-unary-ops': [ 2, { 'words': true, 'nonwords': true, 'overrides': { '!': false, '!!': false } } ],
        'spaced-comment': [ 2, 'always' ],
        'unicode-bom': 0,
        'wrap-regex': 0
    }
};